### Excersises from

https://www.machinelearningplus.com/python/101-numpy-exercises-python/


#### 1. Import numpy as np and print the version number.

In [1]:
import numpy

print(numpy.__version__)

1.18.1


In [2]:
# additional
print("type(numpy.__version__)")
print(type(numpy.__version__), end="\n\n")

print("Lets see what we get by just printing numpy")
print(numpy)

type(numpy.__version__)
<class 'str'>

Lets see what we get by just printing numpy
<module 'numpy' from 'C:\\Users\\ajeyj\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>


#### 2. Create a 1D array of numbers from 0 to 9

In [3]:
_1d_array = numpy.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("array : ", _1d_array)
print("shape : ", _1d_array.shape, end="\n\n")

array :  [0 1 2 3 4 5 6 7 8 9]
shape :  (10,)



In [4]:
# additional
_1d_array = numpy.empty((1,))
print("_1d_array = numpy.empty((1,))")
print("array : ", _1d_array)
print("shape : ", _1d_array.shape, end="\n\n")

_1d_array = numpy.full((1,), fill_value=0)
print("_1d_array = numpy.full((1,), fill_value=0)")
print("array : ", _1d_array)
print("shape : ", _1d_array.shape, end="\n\n")

_1d_array = numpy.zeros((1,))
print("_1d_array = numpy.zeros((1,))")
print("array : ", _1d_array)
print("shape : ", _1d_array.shape, end="\n\n")

_1d_array = numpy.empty((0,))
print("_1d_array = numpy.empty((0,))")
print("array : ", _1d_array)
print("shape : ", _1d_array.shape, end="\n\n")

_1d_array = numpy.array([])
print("_1d_array = numpy.array([])")
print("array : ", _1d_array)
print("shape : ", _1d_array.shape, end="\n\n")

_1d_array = numpy.array([1])
print("_1d_array = numpy.array([1])")
print("array : ", _1d_array)
print("shape : ", _1d_array.shape, end="\n\n")

_1d_array = numpy.empty((1,))
array :  [0.0078125]
shape :  (1,)

_1d_array = numpy.full((1,), fill_value=0)
array :  [0]
shape :  (1,)

_1d_array = numpy.zeros((1,))
array :  [0.]
shape :  (1,)

_1d_array = numpy.empty((0,))
array :  []
shape :  (0,)

_1d_array = numpy.array([])
array :  []
shape :  (0,)

_1d_array = numpy.array([1])
array :  [1]
shape :  (1,)



#### 3. Create a 3×3 numpy array of all True’s

In [5]:
_3_3_arr = numpy.full((3,3), fill_value=True)
print(_3_3_arr)
print(_3_3_arr.dtype)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
bool


In [6]:
# additional
"""
Note:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html

Array of uninitialized (arbitrary) data of the given shape, dtype, and order. 
Object arrays will be initialized to None.

"""

_3_3_arr = numpy.empty((3,3), dtype=bool)
print(_3_3_arr)
print(_3_3_arr.dtype)



[[ True  True  True]
 [ True  True  True]
 [False False False]]
bool


#### Extract all odd numbers from arr

In [7]:
arr = numpy.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd = numpy.array([a for a in range(0, len(arr)) if a % 2])
print(odd)

[1 3 5 7 9]


In [9]:
# additional
arr = numpy.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = arr[arr % 2 == 1]
print(arr)

[1 3 5 7 9]


#### Replace all odd numbers in arr with -1

In [17]:
arr = numpy.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
